server:
  port: 5151

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&socketTimeout=60000&autoReconnectForPools=true&useSSL=true&verifyServerCertificate=false&serverTimezone=UTC
    username: vibeuser
    password: I*O(P)
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  global-config:
    db-config:
      #驼峰下划线转换
      column-underline: true
  #  configuration:
  #    map-underscore-to-camel-case: false
  mapperLocations:
    - classpath:resources/mapper/**.xml


logging:
  level:
    com.cizing.office: debug

